In [1]:
import pandas as pd

In [3]:
OR_dic = pd.read_csv('OR_dict.csv')

In [4]:
OR_dic

,abbreviation,full_spell,word,word_count,odds_ratio
0,MHP,median hinge point,Non-PKU,0,4.753086
1,MHP,median hinge point,mild,0,0.120879
2,MHP,median hinge point,hyperphenylalaninemia,0,0.206529
3,MHP,median hinge point,MHP,13,1.390244
4,MHP,median hinge point,--,1,9.192000
...,...,...,...,...,...
5297970,IDMS,infants of diabetic mothers,AMP,1,12.700599
5297971,IDMS,infants of diabetic mothers,Forty-eight,1,12.700599
5297972,IDMS,infants of diabetic mothers,premature,1,12.700599
5297973,IDMS,infants of diabetic mothers,skinfold,1,12.700599
5297974,IDMS,infants of diabetic mothers,SFT,1,12.700599

In [5]:
df_filtered = OR_dic[OR_dic['word_count'] != 0]
df_filtered

,abbreviation,full_spell,word,word_count,odds_ratio
3,MHP,median hinge point,MHP,13,1.390244
4,MHP,median hinge point,--,1,9.192000
33,MHP,median hinge point,The,1,0.210213
39,MHP,median hinge point,evidence,1,2.618824
40,MHP,median hinge point,date,1,2.330526
...,...,...,...,...,...
5297970,IDMS,infants of diabetic mothers,AMP,1,12.700599
5297971,IDMS,infants of diabetic mothers,Forty-eight,1,12.700599
5297972,IDMS,infants of diabetic mothers,premature,1,12.700599
5297973,IDMS,infants of diabetic mothers,skinfold,1,12.700599
5297974,IDMS,infants of diabetic mothers,SFT,1,12.700599

In [6]:
# Sort by 'full_spell' and 'odds_ratio' in descending order
df_grouped_sorted = df_filtered.sort_values(by=['full_spell', 'odds_ratio'], ascending=[True, False])
df_grouped_sorted.to_csv('OR1_WC_dict.csv', index=False)

In [7]:
df_grouped_sorted

,abbreviation,full_spell,word,word_count,odds_ratio
1153327,APC,activated protein c,anticoagulant,2,8329.000000
1153289,APC,activated protein c,neuroprotective,1,3569.571429
1153291,APC,activated protein c,vessel,1,3569.571429
1153293,APC,activated protein c,stroke,1,3569.571429
1153294,APC,activated protein c,postischemic,1,3569.571429
...,...,...,...,...,...
1377423,WT,wortmannin,weight,1,0.053724
1385281,WT,wortmannin,weigh,1,0.053264
1377532,WT,wortmannin,eight,1,0.050219
1386654,WT,wortmannin,Wi,2,0.049504
1393403,WT,wortmannin,l,140,0.042896

In [8]:
df_top300 = df_grouped_sorted.groupby('full_spell').head(1)
df_top300.to_csv('OR1_WC_top1.csv', index=False)

In [9]:
df_top300

,abbreviation,full_spell,word,word_count,odds_ratio
1153327,APC,activated protein c,anticoagulant,2,8329.000000
3982390,AS,active sleep,sleep,117,5211.272401
1702853,A-T,adenine-thymine,adenine-thymine,66,18161.888889
238205,APC,adenomatous polyposis coli,us,1977,1509.456350
1978995,AD,adenovirus,virus,325,448973.000000
...,...,...,...,...,...
3489229,WD,wolffian duct,Wolffian,50,128573.000000
3338582,WFS,wolfram syndrome,Wolfram,78,10833.000000
1363214,WD,wolman disease,Wolman,46,118637.000000
1102765,WFS,world fertility survey,World,21,13889.000000
1391350,WT,wortmannin,wortmannin,119,23904.686275